name: qolsys_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 3rd party packages and their URLs and licenses
  # Please format accordingly when adding a new package

  # https://pub.dev/packages/cupertino_icons
  # License: MIT (https://github.com/flutter/cupertino_icons/blob/master/LICENSE)
  cupertino_icons: ^1.0.0

  # https://pub.dev/packages/font_awesome_flutter
  # License: MIT (https://github.com/fluttercommunity/font_awesome_flutter/blob/master/LICENSE)
  font_awesome_flutter: ^8.10.0

  # https://pub.dev/packages/flutter_svg
  # License: MIT (https://github.com/dnfield/flutter_svg/blob/master/LICENSE)
  flutter_svg: ^0.18.0

  # https://pub.dev/packages/retrofit
  # License: MIT (https://github.com/trevorwang/retrofit.dart/blob/master/LICENSE)
  retrofit: any

  # https://pub.dev/packages/logger
  # License: MIT (https://github.com/leisim/logger/blob/master/LICENSE)
  logger: any  #for logging purpose

  # https://pub.dev/packages/json_annotation
  # License: BSD (https://github.com/google/json_serializable.dart/blob/master/LICENSE)
  json_annotation: ^3.0.1

  # https://pub.dev/packages/json_serializable
  # License: BSD (https://github.com/google/json_serializable.dart/blob/master/LICENSE)
  json_serializable: ^3.4.0

  # https://pub.dev/packages/provider
  # License: MIT (https://github.com/rrousselGit/provider/blob/master/LICENSE)
  provider: ^4.3.2+2

  # https://pub.dev/packages/intl
  # License: BSD (https://github.com/dart-lang/intl/blob/master/LICENSE)
  intl: ^0.16.1

  # https://pub.dev/packages/flutter_secure_storage
  # License: BSD (https://github.com/mogol/flutter_secure_storage/blob/master/LICENSE)
  flutter_secure_storage: ^3.3.5

  # https://pub.dev/packages/hive
  # License: Apache 2.0 (https://github.com/hivedb/hive/blob/master/hive/LICENSE)
  hive: ^1.4.4+1

  # https://pub.dev/packages/hive_flutter
  # License: Apache 2.0 (https://github.com/hivedb/hive/blob/master/hive_flutter/LICENSE)
  hive_flutter: ^0.3.1

  # https://pub.dev/packages/jwt_decoder
  # License: MIT (https://github.com/gustavo0197/dart-jwt-decoder/blob/master/LICENSE)
  jwt_decoder: ^1.0.3

  # https://pub.dev/packages/easy_localization
  # License: MIT (https://github.com/aissat/easy_localization/blob/master/LICENSE)
  easy_localization: ^2.3.3

  # https://pub.dev/packages/package_info
  # License: BSD (https://github.com/flutter/plugins/blob/master/packages/package_info/LICENSE)
  package_info: ^0.4.3

  # https://pub.dev/packages/smooth_page_indicator
  # License: MIT (https://github.com/Milad-Akarie/smooth_page_indicator/blob/master/LICENSE)
  smooth_page_indicator: ^0.2.0

  # https://pub.dev/packages/fluttertoast
  # License: MIT (https://github.com/PonnamKarthik/FlutterToast/blob/master/LICENSE)
  fluttertoast: ^7.0.2

  # https://pub.dev/packages/firebase_messaging
  # License: BSD
  firebase_messaging: ^7.0.3

  # https://pub.dev/packages/platform_device_id
  # License: BSD (https://github.com/BestBurning/platform_device_id/blob/master/LICENSE)
  platform_device_id: ^0.1.3
  firebase_crashlytics: ^0.2.4
  firebase_core : ^0.5.0
  synchronized: ^2.2.0+2


dev_dependencies:
  # https://pub.dev/packages/test
  # License: BSD (https://github.com/dart-lang/test/blob/master/pkgs/test/LICENSE)
  test: ^1.15.7
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test: ^1.0.1 

  # https://pub.dev/packages/retrofit_generator
  # License: MIT (https://github.com/trevorwang/retrofit.dart/blob/master/LICENSE)
  retrofit_generator: 1.4.0+2

  # https://pub.dev/packages/build_runner
  # License: BSD (https://github.com/dart-lang/build/blob/master/build_runner/LICENSE)
  build_runner: 1.10.7

  # https://pub.dev/packages/analyzer
  # License: BSD (https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/LICENSE)
  analyzer: 0.40.6

  # https://pub.dev/packages/hive_generator
  # License: Apache 2.0 (https://github.com/hivedb/hive/blob/master/hive_generator/LICENSE)
  hive_generator: 0.8.2

  # https://pub.dev/packages/mockito
  # License: Apache 2.0 (https://github.com/dart-lang/mockito/blob/master/LICENSE)
  mockito: ^4.1.3

  # https://pub.dev/packages/flutter_launcher_icons
  # License: MIT (https://github.com/fluttercommunity/flutter_launcher_icons/blob/master/LICENSE)
  flutter_launcher_icons: "^0.8.1"

  # https://pub.dev/packages/flutter_launcher_name
  # License: BSD (https://github.com/daisuke-fukuda/flutter_launcher_name/blob/master/LICENSE)
  flutter_launcher_name: "^0.0.1"

  # https://pub.dev/packages/dotenv
  # License: MIT (https://github.com/mockturtl/dotenv/blob/master/LICENSE)
  dotenv: ^2.0.0

flutter_icons:
    android: true
    ios: true
    image_path_android: "assets/images/png/ic_launcher.png"
    image_path_ios: "assets/images/png/ic_ios_launcher.png"

flutter_launcher_name:
  name: "Qolsys"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/png/
    - assets/translations/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Brandon_light
      fonts:
        - asset: assets/fonts/Brandon_light.otf
          weight: 400
    - family: Brandon_reg
      fonts:
        - asset: assets/fonts/Brandon_reg.otf
          weight: 400
    - family: Brandon_med
      fonts:
        - asset: assets/fonts/Brandon_med.otf
          weight: 400
    - family: Brandon_bld
      fonts:
        - asset: assets/fonts/Brandon_bld.otf
          weight: 400
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
